### PR TITLE
Randomly Generated Passwords

### PR DESCRIPTION
**Pull request by RobloxArchiver**
Uses `secrets` to randomly generate a password

### CODE REVIEW

**Comment by luxxispackin** [comment]
Is there a way I can use this?

**Comment by Imagine-YT** [comment]
@luxxispackin do you really want random password? Cuz if y'all want random passwords then its just like 4 lines of code, I'll update it right now 🤷 
Also, to use that, just use his edited commit of this generator. Sadly, I don't know much about GitHub, so I can't help you a lot.

**Comment by luxxispackin** [comment]
@Imagine-YT yes that would be great.

**Comment by RobloxArchiver** [comment]
If you could like you can merge it in with yours. [Here is a guide on how to.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews)

**Comment by RobloxArchiver** [comment]
> Is there a way I can use this?

You can just use my version, or if Imagine accepts the pull you can use it once it's updated.

**Review by luxxispackin — CHANGES_REQUESTED** [review]
Awesome

**Review by luxxispackin — APPROVED** [review]

**Comment by Imagine-YT** [comment]
I'll accept this pull request, just one question, how long is the password generated from your commit? Cuz it seems 25 characters which I'm pretty sure is past Roblox's maximum limit.

**Comment by luxxispackin** [comment]
Roblox limit on a password is 200 characters

**Comment by Imagine-YT** [comment]
uh-
wtf?
aight then, imma trust you and merge this commit or whatever it is (I'm new to github)

**Review by Imagine-YT — APPROVED** [review]

**Comment by Imagine-YT** [comment]
done

**Comment by luxxispackin** [comment]
Works!

**Comment by Imagine-YT** [comment]
Nice! @luxxispackin 
btw I've got some great ideas for the next update 👀

**Comment by luxxispackin** [comment]
I hope so, I love using this!

**Comment by Imagine-YT** [comment]
@luxxispackin I feel happy knowing that someone enjoys using my tool :)
Btw if you want you can add me on discord: Imagine#9106

**Comment by luxxispackin** [comment]
Thanks so much!

**Pull request merged**
